[build-system]
requires = [
  "setuptools>=75.0",
  "scikit-build-core>=0.10",
  "torch>=2.8.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "sgl-kernel"
version = "0.3.21"
description = "Kernel Library for SGLang"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
]
dependencies = []

[tool.wheel]
exclude = [
  "dist*",
  "tests*",
]
